name: hello-world
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Hello-World
        run:  make say-hello
